In [3]:
import pandas as pd

In [4]:
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

In [30]:
file = 'housing_processed.csv'

In [39]:
df = pd.read_csv(file, index_col=0)

In [40]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,0.211155,0.567481,0.784314,0.022331,0.019863,0.008941,0.020556,0.539668,0.902266,0.0,0.0,0.0,1.0,0.0
1,0.212151,0.565356,0.392157,0.180503,0.171477,0.067210,0.186976,0.538027,0.708247,0.0,0.0,0.0,1.0,0.0
2,0.210159,0.564293,1.000000,0.037260,0.029330,0.013818,0.028943,0.466028,0.695051,0.0,0.0,0.0,1.0,0.0
3,0.209163,0.564293,1.000000,0.032352,0.036313,0.015555,0.035849,0.354699,0.672783,0.0,0.0,0.0,1.0,0.0
4,0.209163,0.564293,1.000000,0.041330,0.043296,0.015752,0.042427,0.230776,0.674638,0.0,0.0,0.0,1.0,0.0


In [54]:
# Multi-linear model with library from sklearn

In [55]:
y_attr = 'median_house_value'

In [56]:
X = df.drop(columns=[y_attr])
y = df[y_attr]

In [112]:
from sklearn.linear_model import LinearRegression

In [58]:
sk_lr = LinearRegression()

In [59]:
model = sk_lr.fit(X,y)

In [60]:
model.score(X,y)

0.6454747751244776

In [61]:
model.coef_

array([-0.54771162, -0.48887561,  0.11123883, -0.38689808,  0.96047872,
       -2.8882835 ,  0.96469165,  1.15926121, -0.0484039 , -0.1302998 ,
        0.27333079, -0.0560116 , -0.03861548])

In [62]:
model.intercept_

np.float64(0.543079936811786)

In [63]:
# Multi-linear model without library. Use numpy

In [78]:
ones = np.ones((X.shape[0],1))
X_np = np.hstack((ones, X))
X_np

array([[1.        , 0.21115538, 0.5674814 , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.21215139, 0.565356  , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.21015936, 0.5642933 , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [1.        , 0.31175299, 0.73219979, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.30179283, 0.73219979, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.30976096, 0.72582359, ..., 0.        , 0.        ,
        0.        ]], shape=(20640, 14))

In [79]:
y_np = np.array(y)
y_np

array([0.90226638, 0.70824656, 0.69505074, ..., 0.15938285, 0.14371281,
       0.15340349], shape=(20640,))

In [82]:
X_np_t = np.matrix_transpose(X_np)

In [83]:
from numpy.linalg import inv
y_coeff = np.matmul(inv(np.matmul(X_np_t, X_np)),X_np_t)

In [84]:
params = np.matmul(y_coeff, y_np)
params

array([-11.92867044,  11.61507451,   9.44160171,  -0.36035736,
       -96.35611663, -14.37570285, -39.8138073 , 113.85270734,
         9.92571342,   0.58671334,   0.56760854,   1.10545809,
         1.3239494 ,   1.09297503])

In [86]:
##########################
# Simple Linear Regression
##########################

In [98]:
# With sklearn

In [93]:
X = df[['median_income']]
y = df[y_attr]result = np.multiply(a, b)

In [94]:
# Library based
sk_slr = LinearRegression()

In [95]:
model = sk_slr.fit(X,y)

In [96]:
model.coef_

array([1.24951891])

In [97]:
model.intercept_

np.float64(0.10511157050753589)

In [99]:
# With numpy

In [106]:
X = df['median_income']
x_mean = np.mean(X)
y_mean = np.mean(y)
xy_mean = np.mean(np.multiply(X, y))

sum = 0
for x in X:
    sum+=x**2
x_2_mean = sum/len(X)

In [109]:
slope = (xy_mean-x_mean*y_mean)/(x_2_mean-x_mean**2)

In [110]:
intercept = y_mean-slope*x_mean

In [111]:
slope, intercept

(np.float64(1.249518913730942), np.float64(0.10511157050753678))